#!/bin/bash

while true; do 
	flurryPort=$(docker inspect -f '{{(index (index .NetworkSettings.Ports "9090/tcp") 0).HostPort}}' flurry-1); 
	ncat 127.0.0.1 $flurryPort < /dev/null; 
	if [ $? -eq 0 ]
	then 
		etcdctl set /services/flurry/1 '{"Host": "host", "ipv4_address": ${COREOS_PUBLIC_IPV4}, "port": $flurryPort}' --ttl 30; 
	else 
		etcdctl rm /services/flurry/1; 
	fi; 
        sleep 20; 
done;
